### ISSUE TITLE
getting null pointer exception error

### ISSUE THREAD

**Issue by suds7** [angusyoung84/androidquiz#2]
I'm getting null pointer exception when i logged into the app. I think the problem is the with the intent being null . Intent i = getIntent();   Any help appreciated

```
    Process: com.example.eduardoshinkawa.quiz, PID: 1720
java.lang.NullPointerException
        at com.example.eduardoshinkawa.quiz.MainActivity$2$1$1.onDataChange(MainActivity.java:67)
        at com.firebase.client.core.ValueEventRegistration.fireEvent(ValueEventRegistration.java:42)
        at com.firebase.client.core.view.DataEvent.fire(DataEvent.java:45)
        at com.firebase.client.core.view.EventRaiser$1.run(EventRaiser.java:38)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by eshinkawa** [comment]
Hey there, I am very sorry for the late reply. It's been awhile since I finished this project. I will download and tell what is happening.
